"use client";

import { useMemo, useState } from "react";
import styles from "./lobby-styler.module.css";

type Style={bold:boolean;italic:boolean;underline:boolean;strike:boolean;color:string;size:string;face:string;stroke:boolean;strokeColor:string;strokeThickness:string};
type Part={text:string;color:string;face:string;colorMode:"solid"|"gradient";gradientFrom:string;gradientTo:string};
const presets:{name:string;emoji:string;style:Partial<Style>}[]=[
  {name:"VIP Gold",emoji:"👑",style:{bold:true,italic:false,color:"#FFD700",size:"24",face:"GothamBold",stroke:true,strokeColor:"#5A3A00",strokeThickness:"1"}},
  {name:"Void",emoji:"🟣",style:{bold:true,italic:true,color:"#B46CFF",size:"24",face:"GothamBold",stroke:true,strokeColor:"#160B22",strokeThickness:"2"}},
  {name:"Warning",emoji:"⚠️",style:{bold:true,italic:false,color:"#FF5C5C",size:"24",face:"GothamBold",stroke:true,strokeColor:"#2B0707",strokeThickness:"2"}},
  {name:"Clean",emoji:"✨",style:{bold:false,italic:false,underline:false,strike:false,color:"#FFFFFF",size:"24",face:"Gotham",stroke:false,strokeColor:"#000000",strokeThickness:"1"}},
];
const faces=["Legacy","Arial","ArialBold","SourceSans","SourceSansBold","SourceSansLight","SourceSansItalic","Bodoni","Garamond","Cartoon","Code","Highway","SciFi","Arcade","Fantasy","Antique","SourceSansSemibold","Gotham","GothamMedium","GothamBold","GothamBlack","AmaticSC","Bangers","Creepster","FredokaOne","JosefinSans","Michroma","Roboto","RobotoCondensed","RobotoMono","Ubuntu","BuilderSans","BuilderSansMedium","BuilderSansBold","BuilderSansExtraBold"];
const previewFontStacks:Record<string,string>={Legacy:"Arial,sans-serif",Arial:"Arial,sans-serif",ArialBold:"Arial Black,Arial,sans-serif",SourceSans:"Arial,sans-serif",SourceSansBold:"Arial Black,Arial,sans-serif",SourceSansLight:"Arial,sans-serif",SourceSansItalic:"Arial,sans-serif",Bodoni:"Bodoni 72,Didot,serif",Garamond:"Garamond,serif",Cartoon:"Comic Sans MS,cursive",Code:"ui-monospace,SFMono-Regular,Menlo,monospace",Highway:"Arial Narrow,Arial,sans-serif",SciFi:"Orbitron,Arial,sans-serif",Arcade:"Arial Black,Arial,sans-serif",Fantasy:"Papyrus,fantasy",Antique:"Georgia,serif",SourceSansSemibold:"Arial,sans-serif",Gotham:"Arial,sans-serif",GothamMedium:"Arial,sans-serif",GothamBold:"Arial Black,Arial,sans-serif",GothamBlack:"Impact,Arial Black,sans-serif",AmaticSC:"Amatic SC,cursive",Bangers:"Bangers,Impact,cursive",Creepster:"Creepster,Georgia,cursive",FredokaOne:"Fredoka One,Arial,sans-serif",JosefinSans:"Josefin Sans,Arial,sans-serif",Michroma:"Michroma,Arial,sans-serif",Roboto:"Roboto,Arial,sans-serif",RobotoCondensed:"Roboto Condensed,Arial,sans-serif",RobotoMono:"Roboto Mono,ui-monospace,monospace",Ubuntu:"Ubuntu,Arial,sans-serif",BuilderSans:"Arial,sans-serif",BuilderSansMedium:"Arial,sans-serif",BuilderSansBold:"Arial Black,Arial,sans-serif",BuilderSansExtraBold:"Arial Black,Arial,sans-serif"};
function escapeRichText(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&apos;");}
function safeColor(value:string,fallback="#FFFFFF"){return /^#[0-9a-fA-F]{6}$/.test(value)?value.toUpperCase():fallback;}
function hexToRgb(hex:string){const n=parseInt(hex.slice(1),16);return [n>>16,(n>>8)&255,n&255];}
function rgbToHex(r:number,g:number,b:number){return `#${[r,g,b].map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,"0")).join("").toUpperCase()}`;}
function gradientColors(from:string,to:string,count:number){const a=hexToRgb(safeColor(from)),b=hexToRgb(safeColor(to));return Array.from({length:Math.max(1,count)},(_,i)=>{const t=count<=1?0:i/(count-1);return rgbToHex(a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t);});}
function wrapStyle(result:string,style:Style){const color=safeColor(style.color),strokeColor=safeColor(style.strokeColor,"#000000");if(style.bold)result=`<b>${result}</b>`;if(style.italic)result=`<i>${result}</i>`;if(style.underline)result=`<u>${result}</u>`;if(style.strike)result=`<s>${result}</s>`;result=`<font color=\"${color}\"><font size=\"${style.size}\"><font face=\"${style.face}\">${result}</font></font></font>`;if(style.stroke)result=`<stroke color=\"${strokeColor}\" thickness=\"${style.strokeThickness}\">${result}</stroke>`;return result;}
function buildPartMarkup(part:Part){const text=part.text, chars=Array.from(text), colors=gradientColors(part.gradientFrom,part.gradientTo,chars.filter(c=>c!==" ").length);if(part.colorMode==="solid")return `<font face=\"${part.face}\"><font color=\"${safeColor(part.color)}\">${escapeRichText(text)}</font></font>`;let index=0;const result=chars.map(char=>char===" "?" ":`<font color=\"${colors[index++]}\">${escapeRichText(char)}</font>`).join("");return `<font face=\"${part.face}\">${result}</font>`;}
function buildMarkup(text:string,style:Style,parts:Part[],mode:"single"|"parts"|"gradient",gradientFrom:string,gradientTo:string){let result="";if(mode==="parts")result=parts.map(buildPartMarkup).join("");else if(mode==="gradient"){const chars=Array.from(text||"Your Lobby Name"),colors=gradientColors(gradientFrom,gradientTo,chars.filter(c=>c!==" ").length);let index=0;result=chars.map(char=>char===" "?" ":`<font color=\"${colors[index++]}\">${escapeRichText(char)}</font>`).join("");}else result=escapeRichText(text||"Your Lobby Name");return wrapStyle(result,style);}
function previewMarkup(markup:string){return markup.replace(/<font color=\"(#[0-9a-fA-F]{6})\">/g,"<span style=\"color:$1\">").replace(/<font size=\"(\d+)\">/g,"<span style=\"font-size:${Math.min(64,Number($1))}px\">").replace(/<font face=\"([^\"]+)\">/g,(_,face:string)=>`<span style=\"font-family:${previewFontStacks[face]??"Arial,sans-serif}\" title=\"Roblox font: ${face}\">`).replace(/<stroke color=\"(#[0-9a-fA-F]{6})\" thickness=\"([0-9.]+)\">/g,"<span style=\"-webkit-text-stroke:${$2}px $1\">").replace(/<\/(font|stroke)>/g,"</span>").replace(/<b>/g,"<strong>").replace(/<\/b>/g,"</strong>").replace(/<i>/g,"<em>").replace(/<\/i>/g,"</em>").replace(/<u>/g,"<span style=\"text-decoration:underline\">").replace(/<\/u>/g,"</span>").replace(/<s>/g,"<del>").replace(/<\/s>/g,"</del>");}

export default function LobbyStyler(){
  const [text,setText]=useState("VIP Lobby");
  const [style,setStyle]=useState<Style>({bold:true,italic:false,underline:false,strike:false,color:"#B46CFF",size:"24",face:"GothamBold",stroke:true,strokeColor:"#160B22",strokeThickness:"2"});
  const [parts,setParts]=useState<Part[]>([{text:"VIP",color:"#FFD700",face:"GothamBold",colorMode:"solid",gradientFrom:"#FFD700",gradientTo:"#FF8C00"},{text:" Lobby",color:"#B46CFF",face:"GothamBold",colorMode:"solid",gradientFrom:"#B46CFF",gradientTo:"#4D8DFF"}]);
  const [mode,setMode]=useState<"single"|"parts"|"gradient">("single");
  const [gradientFrom,setGradientFrom]=useState("#FF4DFF");
  const [gradientTo,setGradientTo]=useState("#4D8DFF");
  const [advanced,setAdvanced]=useState(false);
  const [copied,setCopied]=useState(false);
  const markup=useMemo(()=>buildMarkup(text,style,parts,mode,gradientFrom,gradientTo),[text,style,parts,mode,gradientFrom,gradientTo]);
  const preview=useMemo(()=>previewMarkup(markup),[markup]);
  function patch(next:Partial<Style>){setStyle(current=>({...current,...next}));setCopied(false);}
  function splitWords(){const words=text.trim().split(/\s+/).filter(Boolean);if(!words.length)return;setParts(words.map((word,index)=>({text:(index?" ":"")+word,color:index%2?"#B46CFF":"#FFD700",face:style.face,colorMode:"solid",gradientFrom:index%2?"#B46CFF":"#FFD700",gradientTo:index%2?"#4D8DFF":"#FF8C00"})));setMode("parts");setCopied(false);}
  function updatePart(index:number,next:Partial<Part>){setParts(current=>current.map((part,i)=>i===index?{...part,...next}:part));setCopied(false);}
  function handleTextChange(value:string){setText(value);if(mode!=="parts")return;const words=value.trim().split(/\s+/).filter(Boolean);setParts(current=>words.map((word,index)=>({text:(index?" ":"")+word,color:current[index]?.color??(index%2?"#B46CFF":"#FFD700"),face:current[index]?.face??style.face,colorMode:current[index]?.colorMode??"solid",gradientFrom:current[index]?.gradientFrom??(index%2?"#B46CFF":"#FFD700"),gradientTo:current[index]?.gradientTo??(index%2?"#4D8DFF":"#FF8C00")})));setCopied(false);}
  async function copy(){try{await navigator.clipboard.writeText(markup);setCopied(true);setTimeout(()=>setCopied(false),1400);}catch{setCopied(false);}}
  return <section className={styles.editor}>
    <div className={styles.previewCard}><div className={styles.previewLabel}>PREVIEW</div><div className={styles.preview} dangerouslySetInnerHTML={{__html:preview}}/><div className={styles.previewHint}>Colors can be applied to individual words or characters using Roblox RichText.</div></div>
    <div className={styles.controls}>
      <label className={styles.fieldWide}><span>1 · NAME</span><input value={text} maxLength={100} onChange={event=>handleTextChange(event.target.value)} placeholder="VIP Lobby" autoFocus/></label>
      <div className={styles.presetHeading}><span>2 · PICK A STYLE</span><small>Start with a preset — you can customize it below.</small></div>
      <div className={styles.presetGrid}>{presets.map(preset=><button key={preset.name} className={styles.presetCard} type="button" onClick={()=>{setStyle(current=>({...current,...preset.style}));setCopied(false);}}><strong>{preset.emoji} {preset.name}</strong><span>{preset.name==="VIP Gold"?"Premium & shiny":preset.name==="Void"?"Dark & purple":preset.name==="Warning"?"Loud & attention-grabbing":"Simple & clean"}</span></button>)}</div>
      <div className={styles.colorModes}><button className={mode==="single"?styles.active:""} type="button" onClick={()=>setMode("single")}>ONE COLOR</button><button className={mode==="parts"?styles.active:""} type="button" onClick={splitWords}>COLOR WORDS</button><button className={mode==="gradient"?styles.active:""} type="button" onClick={()=>setMode("gradient")}>FULL GRADIENT</button></div>
      {mode==="parts"&&<div className={styles.partsPanel}><div className={styles.partsHeader}><span>COLOR EACH PART</span><small>Each word can use one color or its own gradient. Fonts stay independent too.</small></div>{parts.map((part,index)=><div className={styles.partRow} key={index}><input className={styles.partText} value={part.text} onChange={event=>updatePart(index,{text:event.target.value})}/><select value={part.colorMode} onChange={event=>updatePart(index,{colorMode:event.target.value as Part["colorMode"]})}><option value="solid">SOLID</option><option value="gradient">GRADIENT</option></select>{part.colorMode==="solid"?<><input type="color" value={safeColor(part.color)} onChange={event=>updatePart(index,{color:event.target.value.toUpperCase()})}/><input value={part.color} onChange={event=>updatePart(index,{color:event.target.value})}/></>:<><input type="color" value={safeColor(part.gradientFrom)} onChange={event=>updatePart(index,{gradientFrom:event.target.value.toUpperCase()})}/><input type="color" value={safeColor(part.gradientTo)} onChange={event=>updatePart(index,{gradientTo:event.target.value.toUpperCase()})}/></>}<select value={part.face} onChange={event=>updatePart(index,{face:event.target.value})}>{faces.map(face=><option key={face}>{face}</option>)}</select></div>)}<button className={styles.addPart} type="button" onClick={()=>setParts(current=>[...current,{text:" new",color:"#FFFFFF",face:style.face,colorMode:"solid",gradientFrom:"#FFFFFF",gradientTo:"#888888"}])}>+ ADD PART</button></div>}
      {mode==="gradient"&&<div className={styles.gradientPanel}><div className={styles.partsHeader}><span>FULL TEXT GRADIENT</span><small>This gradients the entire lobby name from START to END. For a gradient on just one word, use COLOR WORDS and choose GRADIENT on that word.</small></div><div className={styles.gradientInputs}><label><span>START</span><input type="color" value={gradientFrom} onChange={event=>setGradientFrom(event.target.value.toUpperCase())}/></label><label><span>END</span><input type="color" value={gradientTo} onChange={event=>setGradientTo(event.target.value.toUpperCase())}/></label></div></div>}
      <button className={styles.advancedToggle} type="button" onClick={()=>setAdvanced(value=>!value)}>{advanced?"▾ HIDE CUSTOMIZATION":"▸ MORE CUSTOMIZATION"}</button>
      {advanced&&<div className={styles.advancedPanel}><div className={styles.buttonRow}>{([["B","bold"],["I","italic"],["U","underline"],["S","strike"]] as const).map(([label,key])=><button key={key} className={style[key]?styles.active:""} onClick={()=>patch({[key]:!style[key]})} aria-label={key} type="button">{label}</button>)}</div><div className={styles.grid}><label><span>COLOR</span><div className={styles.colorInput}><input type="color" value={safeColor(style.color)} onChange={event=>patch({color:event.target.value.toUpperCase()})}/><input value={style.color} onChange={event=>patch({color:event.target.value})} spellCheck={false}/></div></label><label><span>SIZE</span><select value={style.size} onChange={event=>patch({size:event.target.value})}>{["16","20","24","28","32","40","48"].map(size=><option key={size}>{size}</option>)}</select></label><label><span>FONT</span><select value={style.face} onChange={event=>patch({face:event.target.value})}>{faces.map(face=><option key={face}>{face}</option>)}</select></label><label><span>STROKE</span><select value={style.stroke?"on":"off"} onChange={event=>patch({stroke:event.target.value==="on"})}><option value="on">ON</option><option value="off">OFF</option></select></label></div>{style.stroke&&<div className={styles.grid}><label><span>STROKE COLOR</span><div className={styles.colorInput}><input type="color" value={safeColor(style.strokeColor,"#000000")} onChange={event=>patch({strokeColor:event.target.value.toUpperCase()})}/><input value={style.strokeColor} onChange={event=>patch({strokeColor:event.target.value})} spellCheck={false}/></div></label><label><span>STROKE WIDTH</span><select value={style.strokeThickness} onChange={event=>patch({strokeThickness:event.target.value})}>{["0.5","1","1.5","2","3","4"].map(size=><option key={size}>{size}</option>)}</select></label></div>}</div>}
    </div>
    <div className={`${styles.output} lobby-styler-output`}><div><span>3 · COPY THIS</span><small>Paste this into your VIP lobby name field with RichText enabled.</small></div><code>{markup}</code><button type="button" onClick={copy}>{copied?"COPIED ✓":"COPY RICHTEXT"}</button></div>
  </section>;
}
